apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: healthapp-backend-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ORG/healthapp-k8s
    targetRevision: HEAD
    path: environments/dev
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.repository
          value: ghcr.io/OWNER/healthapp-backend
        - name: image.tag
          value: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
