apiVersion: v1
kind: Service
metadata:
  name: {{ include "healthapp-backend.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "healthapp-backend.name" . }}
