name: helm-ct
on:
  pull_request:
    paths:
      - 'charts/**'
permissions:
  contents: read

jobs:
  ct-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
      - name: Setup chart-testing
        uses: helm/chart-testing-action@v2.6.1
      - name: Run chart-testing (lint + version bump)
        run: |
          ct lint --all --chart-dirs charts --validate-maintainers=false --check-version-increment=true
